SmartExam-salesforce/force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <displayFormat>ANS-{0000}</displayFormat>
        <label>Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SmartExam-salesforce/force-app/main/default/objects/Exam_Attempt__c/Exam_Attempt__c.object-meta.xml
<CustomObject>
    <label>Exam Attempt</label>
    <nameField>
        <displayFormat>ATT-{0000}</displayFormat>
        <label>Attempt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Attempts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SmartExam-salesforce/force-app/main/default/objects/Exam_Attempt__c/fields/Exam_Config__c.field-meta.xml
<CustomField>
    <fullName>Exam_Config__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exam Config</label>
    <referenceTo>Exam_Config__c</referenceTo>
    <relationshipLabel>Exam Attempts</relationshipLabel>
    <relationshipName>Exam_Attempts</relationshipName>
    <type>Lookup</type>
</CustomField>

SmartExam-salesforce/force-app/main/default/objects/Exam_Attempt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Auto Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SmartExam-salesforce/force-app/main/default/objects/Exam_Config__c/Exam_Config__c.object-meta.xml
<CustomObject>
    <label>Exam Config</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exam Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SmartExam-salesforce/force-app/main/default/objects/Exam_Config__c/fields/Passing_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Passing_Percentage__c</fullName>
    <defaultValue>65</defaultValue>
    <label>Passing Percentage</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

SmartExam-salesforce/force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SmartExam-salesforce/force-app/main/default/objects/Question__c/fields/Marks__c.field-meta.xml
<CustomField>
    <fullName>Marks__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Marks</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SmartExam-salesforce/force-app/main/default/objects/Question__c/fields/Question_Text__c.field-meta.xml
<CustomField>
    <fullName>Question_Text__c</fullName>
    <label>Question Text</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

SmartExam-salesforce/force-app/main/default/objects/Question__c/fields/Question_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Type__c</fullName>
    <label>Question Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single Choice</fullName>
            </value>
            <value>
                <fullName>Multiple Choice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SmartExam-salesforce/force-app/main/default/objects/Response__c/Response__c.object-meta.xml
<CustomObject>
    <label>Response</label>
    <nameField>
        <displayFormat>RES-{0000}</displayFormat>
        <label>Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SmartExam-salesforce/force-app/main/default/objects/Response__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Answer</label>
    <referenceTo>Answer__c</referenceTo>
    <relationshipLabel>Responses</relationshipLabel>
    <relationshipName>Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

SmartExam-salesforce/force-app/main/default/objects/Response__c/fields/Exam_Attempt__c.field-meta.xml
<CustomField>
    <fullName>Exam_Attempt__c</fullName>
    <label>Exam Attempt</label>
    <referenceTo>Exam_Attempt__c</referenceTo>
    <relationshipLabel>Responses</relationshipLabel>
    <relationshipName>Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

SmartExam-salesforce/force-app/main/default/objects/Response__c/fields/Is_Selected__c.field-meta.xml
<CustomField>
    <fullName>Is_Selected__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Selected</label>
    <type>Checkbox</type>
</CustomField>

SmartExam-salesforce/force-app/main/default/objects/Response__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Responses</relationshipLabel>
    <relationshipName>Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

SmartExam-salesforce/force-app/main/default/classes/ResultServiceTest.cls
@IsTest
private class ResultServiceTest {

    @TestSetup
    static void setupData() {

        // Create Exam Configuration
        Exam_Config__c examConfig = new Exam_Config__c(
            Name = 'Mock Exam',
            Duration_Minutes__c = 60,
            Number_of_Questions__c = 1,
            Passing_Percentage__c = 50,
            Active__c = true
        );
        insert examConfig;

        // Create Question
        Question__c question = new Question__c(
            Question_Text__c = 'What is Salesforce?',
            Question_Type__c = 'Single Choice',
            Marks__c = 5,
            Active__c = true
        );
        insert question;

        // Create Answers
        Answer__c correctAnswer = new Answer__c(
            Question__c = question.Id,
            Answer_Text__c = 'CRM',
            Is_Correct__c = true
        );

        Answer__c wrongAnswer = new Answer__c(
            Question__c = question.Id,
            Answer_Text__c = 'Compiler',
            Is_Correct__c = false
        );

        insert new List<Answer__c>{
            correctAnswer,
            wrongAnswer
        };

        // Create Exam Attempt
        Exam_Attempt__c attempt = new Exam_Attempt__c(
            Student_Name__c = 'Anushka',
            Student_Email__c = 'anushka@test.com',
            Start_Time__c = System.now(),
            Status__c = 'In Progress',
            Exam_Config__c = examConfig.Id
        );
        insert attempt;

        // Create Response
        Response__c response = new Response__c(
            Exam_Attempt__c = attempt.Id,
            Question__c = question.Id,
            Answer__c = correctAnswer.Id,
            Is_Selected__c = true
        );
        insert response;
    }

    @IsTest
    static void testCalculateScore() {

        Exam_Attempt__c attempt = [
            SELECT Id
            FROM Exam_Attempt__c
            LIMIT 1
        ];

        Test.startTest();

        Decimal score =
            ResultService.calculateScore(attempt.Id);

        Test.stopTest();

        System.assertEquals(5, score);
    }

    @IsTest
    static void testSubmitExam() {

        Exam_Attempt__c attempt = [
            SELECT Id
            FROM Exam_Attempt__c
            LIMIT 1
        ];

        Test.startTest();

        ResultService.submitExam(attempt.Id);

        Test.stopTest();

        Exam_Attempt__c updatedAttempt = [
            SELECT Score__c,
                   Status__c,
                   End_Time__c
            FROM Exam_Attempt__c
            WHERE Id = :attempt.Id
        ];

        System.assertEquals(5, updatedAttempt.Score__c);
        System.assertEquals('Completed', updatedAttempt.Status__c);
        System.assertNotEquals(null, updatedAttempt.End_Time__c);
    }

}