SmartExam-salesforce/force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <displayFormat>ANS-{0000}</displayFormat>
        <label>Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SmartExam-salesforce/force-app/main/default/objects/Exam_Attempt__c/Exam_Attempt__c.object-meta.xml
<CustomObject>
    <label>Exam Attempt</label>
    <nameField>
        <displayFormat>ATT-{0000}</displayFormat>
        <label>Attempt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Attempts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SmartExam-salesforce/force-app/main/default/objects/Exam_Attempt__c/fields/Exam_Config__c.field-meta.xml
<CustomField>
    <fullName>Exam_Config__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exam Config</label>
    <referenceTo>Exam_Config__c</referenceTo>
    <relationshipLabel>Exam Attempts</relationshipLabel>
    <relationshipName>Exam_Attempts</relationshipName>
    <type>Lookup</type>
</CustomField>

SmartExam-salesforce/force-app/main/default/objects/Exam_Attempt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Auto Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SmartExam-salesforce/force-app/main/default/objects/Exam_Config__c/Exam_Config__c.object-meta.xml
<CustomObject>
    <label>Exam Config</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exam Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SmartExam-salesforce/force-app/main/default/objects/Exam_Config__c/fields/Passing_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Passing_Percentage__c</fullName>
    <defaultValue>65</defaultValue>
    <label>Passing Percentage</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

SmartExam-salesforce/force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SmartExam-salesforce/force-app/main/default/objects/Question__c/fields/Marks__c.field-meta.xml
<CustomField>
    <fullName>Marks__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Marks</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SmartExam-salesforce/force-app/main/default/objects/Question__c/fields/Question_Text__c.field-meta.xml
<CustomField>
    <fullName>Question_Text__c</fullName>
    <label>Question Text</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

SmartExam-salesforce/force-app/main/default/objects/Question__c/fields/Question_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Type__c</fullName>
    <label>Question Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single Choice</fullName>
            </value>
            <value>
                <fullName>Multiple Choice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SmartExam-salesforce/force-app/main/default/classes/ExamServiceTest.cls
@IsTest
private class ExamServiceTest {

    @TestSetup
    static void setupData() {

        Exam_Config__c examConfig = new Exam_Config__c(
            Name = 'Mock Exam',
            Duration_Minutes__c = 60,
            Number_of_Questions__c = 2,
            Passing_Percentage__c = 50,
            Active__c = true
        );
        insert examConfig;

        Question__c q1 = new Question__c(
            Question_Text__c = 'What is Salesforce?',
            Question_Type__c = 'Single Choice',
            Marks__c = 5,
            Active__c = true
        );
        insert q1;

        Question__c q2 = new Question__c(
            Question_Text__c = 'Select CRM Platforms',
            Question_Type__c = 'Multiple Choice',
            Marks__c = 5,
            Active__c = true
        );
        insert q2;

        insert new List<Answer__c>{
            new Answer__c(
                Question__c = q1.Id,
                Answer_Text__c = 'CRM',
                Is_Correct__c = true
            ),
            new Answer__c(
                Question__c = q1.Id,
                Answer_Text__c = 'Compiler',
                Is_Correct__c = false
            ),
            new Answer__c(
                Question__c = q2.Id,
                Answer_Text__c = 'Salesforce',
                Is_Correct__c = true
            ),
            new Answer__c(
                Question__c = q2.Id,
                Answer_Text__c = 'HubSpot',
                Is_Correct__c = true
            ),
            new Answer__c(
                Question__c = q2.Id,
                Answer_Text__c = 'Photoshop',
                Is_Correct__c = false
            )
        };
    }

    @IsTest
    static void testStartExam() {

        Test.startTest();

        Id attemptId = ExamService.startExam(
            'Anushka',
            'anushka@test.com'
        );

        Test.stopTest();

        System.assertNotEquals(null, attemptId);

        Exam_Attempt__c attempt = [
            SELECT Student_Name__c,
                   Student_Email__c,
                   Status__c
            FROM Exam_Attempt__c
            WHERE Id = :attemptId
        ];

        System.assertEquals('Anushka', attempt.Student_Name__c);
        System.assertEquals('anushka@test.com', attempt.Student_Email__c);
        System.assertEquals('In Progress', attempt.Status__c);
    }

    @IsTest
    static void testGetExamAttempt() {

        Id attemptId = ExamService.startExam(
            'Student',
            'student@test.com'
        );

        Test.startTest();

        Exam_Attempt__c attempt =
            ExamService.getExamAttempt(attemptId);

        Test.stopTest();

        System.assertEquals('Student', attempt.Student_Name__c);
    }

    @IsTest
    static void testGetActiveExamConfig() {

        Test.startTest();

        Exam_Config__c config =
            ExamService.getActiveExamConfig();

        Test.stopTest();

        System.assertNotEquals(null, config);
        System.assertEquals(true, config.Active__c);
    }

    @IsTest
    static void testValidateExamConfiguration() {

        Test.startTest();

        ExamService.validateExamConfiguration();

        Test.stopTest();

        System.assert(true);
    }

}